name: WizardCore CI

on:
  push:
    branches: [staging, main]
    tags:     ["v*"]          # any tag that starts with “v”
  pull_request:
    branches: [staging]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # 1. Fetch the code
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # 2. (Optional) run unit tests – skip for now
    # You can add GUT or other tests here later

    # 3. Build the ZIP — everything under addons/wizardcore
    - name: Pack plug-in
      run: |
        zip -r wizardcore.zip addons/wizardcore README.md

    # 4a. Upload as *Artifact* for branch builds
    - name: Upload artifact
      if: github.ref_type == 'branch'
      uses: actions/upload-artifact@v4
      with:
        name: wizardcore-${{ github.ref_name }}
        path: wizardcore.zip

    # 4b. Create / update GitHub Release for tags
    - name: Publish GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: wizardcore.zip
        generate_release_notes: true
